services:
  # Frontend React App
  - type: web
    name: lms-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://lms-app-backend-nobf.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Node.js API
  - type: web
    name: lms-app-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://your-mongodb-uri
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: NODE_ENV
        value: production 