services:
  # Backend API Service
  - type: web
    name: lms-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend Web Service
  - type: web
    name: lms-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: http://localhost:5000
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false 